include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_final_locals: true
    prefer_single_quotes: true
    newline_at_end_of_file: true

analyzer:
  plugins:
    - flutter
