name: Flutter Test

on:
  pull_request:
    paths:
      - 'mobile-app/**'
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: flutter-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: stable
      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile-app
      - name: Analyze Flutter code
        run: flutter analyze --no-pub
        working-directory: mobile-app
      - name: Run service package tests
        run: |
          flutter pub get
          flutter test --dart-define=VITE_NEWSDATA_KEY=test
        working-directory: mobile-app/packages/services
      - name: Run Flutter tests
        run: flutter test --dart-define=VITE_NEWSDATA_KEY=test
        working-directory: mobile-app
