name: smwa_services
version: 0.1.0
description: Stub services for SMWA
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
